# http://docs.travis-ci.com/user/languages/objective-c/
osx_image: beta-xcode6.3
language: objective-c
xcode_project: LXSupportKit.xcodeproj
xcode_scheme: LXSupportKit
xcode_sdk: iphonesimulator

before_install:
  - bundle install --without=documentation

after_success:
  - bundle exec slather
